
- name: Deploy a webserver locally using Docker
  hosts: myhosts
  connection: local
  tasks:
          - name: Install Docker
            package:
                    name: docker-ce
                    state: present

          - name: Start Docker
            service:
                    name: docker
                    enabled: true 

          - name: Clone Git repo
            git:
                    repo: git@github.com:robertmercea/ansible-playbook-test.git
                    clone: true 
                    update: true
                    dest: ./server

          - name: Build server image
            community.docker.docker_image_build:
                    name: web-server
                    dockerfile: server.Dockerfile
                    path: ./server

          - name: Run container 
            community.docker.docker_container:
                    image: web-server
                    name: my-web-server
                    state: started
                    command: python3 -m http.server 1234
                    ports:
                            - "1234:1234"

          - name: Copy web data into container 
            community.docker.docker_container_copy_into:
                    container: my-web-server
                    container_path: /home/
                    path: ./server/web/index.html

