- name: Import handlers
  import_tasks: ../../deploy/handlers/main.yaml
  notify:
    - Get current page content
    - Print page content

- name: Change page content
  copy:
    src:  web/index2.html
    dest: web/index.html
  notify:
    - Get current page content
    - Print page content

