- name: Import handlers
  import_tasks: ../../deploy/handlers/main.yaml
  notify:
    - Get current page content
    - Print page content

- name: Change page content
  community.docker.docker_container_copy_into:
    container: homework-2-server-1
    container_path: /usr/share/nginx/html/index.html
    path: ./web/index2.html
  notify:
    - Get current page content
    - Print page content

